import Iridescence from "@/components/Iridescence";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/components/react-query-provider";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReactQueryProvider>
          <Toaster richColors />
          <div className="fixed inset-0 -z-10">
            <Iridescence
              color={[0.8157, 0.3373, 0.4157]}
              mouseReact={false}
              amplitude={0.1}
              speed={0.5}
            />
          </div>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
