/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ..\..\3D\assets\logo.glb --transform --format png --resolution 4096 -t -r public 
Files: ..\..\3D\assets\logo.glb [81.93MB] > D:\Works\Coding-Stuffs\WDP\artchain-web\logo-transformed.glb [41.08MB] (50%)
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { JSX, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    node_0: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

const url =
  "https://firebasestorage.googleapis.com/v0/b/artchain-c46a7.firebasestorage.app/o/3D-models%2Flogo-transformed.glb?alt=media&token=a67625f3-bf9f-4360-a275-c055d29a64b7";
export function Logo(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(url) as unknown as GLTFResult;
  const ref = useRef<THREE.Group>(null);

  useFrame((_, delta) => {
    if (ref.current) {
      ref.current.rotation.y += delta;
    }
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.node_0.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(url);
