/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ..\..\3D\assets\mascot.glb --transform --format png --resolution 4096 -t -r public 
Files: ..\..\3D\assets\mascot.glb [84.21MB] > D:\Works\Coding-Stuffs\WDP\artchain-web\mascot-transformed.glb [47.4MB] (44%)
*/

import { useGLTF } from "@react-three/drei";
import { JSX } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    node_0: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

const url =
  "https://firebasestorage.googleapis.com/v0/b/artchain-c46a7.firebasestorage.app/o/3D-models%2Fmascot-transformed.glb?alt=media&token=6ae203c8-703f-4856-962d-39588e068f6d";
export function Mascot(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(url) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.node_0.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(url);
